# Site settings
title: "CanInvest | Private Investment Office, Edinburgh"
email: info@caninvest.uk
url: https://www.caninvest.uk
description: "Private Investment Office"
meta_description: "CanInvest is a private investment office based in Edinburgh, specialising in equities, bonds and real estate investments."

# Color settings
color:
  primary-dark: '#1a1a1a'
  links: '#a88595'

# Background
background_image: /img/private-investment-office.jpg

# Build settings
markdown: kramdown
permalink: pretty
theme: null
